################################
# when a droid is provisioned either by the Droidnet or Standalone
# the approriate subdirectory will be copied to the root
# In the droidnet the MASTER controls eveything!
# min and max are servo setting from 500-2400
# inv_ will flip the direction of the servo
# torso_turn = pin12 , head_turn = pin13, head_tilt = pin 14
# Standalone.ini has Stand alone specific settings
################################
min_head_turn=1100
max_head_turn=1900
inv_head_turn=0
min_head_tilt=1100
max_head_tilt=1900
inv_head_tilt=0
min_torso_turn=1100
max_torso_turn=1900
inv_torso_turn=0
##### below this line is written by the system
vol=10
mode=NET_MANUAL
id=1
