#################################
# Standalone Mode
# When in the mode the system will wait the minDelay in seconds
# then randomly pick a sequence from the Standalone directory 
# ###############################
# Sound True/False to enable Audio
Sound=True
# movement True/False to enable servos
Movement=True
# MinDelay in seconds between random sequences
MinDelay=10